### ISSUE TITLE
Probability of circle/square not 50/50

### ISSUE THREAD

**Issue by JannisBush** [magpie-ea/magpie-mental-chronometry#2]
I just copied the the structure of the trials from the old version.

Is it on purpose that the probability for circle/square is not 50/50 and is not the same for all tasks?

https://github.com/babe-project/MentalChronometry/blob/a7c1166064a25d004a82c8e18d4b45cf1ed8559c/trials.js#L110

**Comment by michael-franke** [comment]
No, it isn’t! Can you fix it (easily)?
